---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 1
provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04

  - name: centos-5.10
  - name: centos-6.4
  - name: centos-6.5

  - name: fedora-19
  - name: fedora-20

suites:
  - name: default
    run_list:
      - recipe[openstack-clients::default]
#  - name: nova
#    run_list:
#      - recipe[openstack-clients::nova]
#  - name: glance
#    run_list:
#      - recipe[openstack-clients::glance]
#  - name: swift
#    run_list:
#      - recipe[openstack-clients::swift]
#  - name: ceilometer
#    run_list:
#      - recipe[openstack-clients::ceilometer]
#  - name: neutron
#    run_list:
#      - recipe[openstack-clients::neutron]
#  - name: cinder
#    run_list:
#      - recipe[openstack-clients::cinder]
#  - name: trove
#    run_list:
#      - recipe[openstack-clients::trove]
#  - name: barbican
#    run_list:
#      - recipe[openstack-clients::barbican]
#  - name: sahara
#    run_list:
#      - recipe[openstack-clients::sahara]
