---
driver:
  name: docker

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.4
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list: ["recipe[openstack-clients]"]
  attributes: {}
