---
driver:
  name: digitalocean

platforms:
- name: ubuntu-12-04-x64
  driver_config:
    region: nyc3
    size: 512mb
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

suites:
- name: default
  run_list: ['recipe[openstack-clients::default]']
  attributes: {}
