---
driver:
  name: docker

provisioner:
  name: chef_zero
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: centos-6
- name: fedora-20
- name: fedora-21

suites:
- name: default
  run_list: ["recipe[openstack-clients]"]
  attributes: {}
