---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  region: us-east-1
  availability_zone: us-east-1b
  username: ubuntu
  flavor_id: t1.micro
  interface: public
  price: <%= ENV['AWS_PRICE'] %>

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list: ['recipe[openstack-clients::default]']
  attributes: {}
