---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04

  - name: centos-5.10
  - name: centos-6.5

  - name: fedora-19
  - name: fedora-20

suites:
  - name: default
    run_list:
      - recipe[openstack-clients::default]

  - name: openstackrc
    run_list:
      - recipe[openstack-clients::openstackrc]
    attributes:
      openstack-clients:
        openstackrc:
          configs:
            project1:
              OS_AUTH_URL: 'https://identity.project1.openstack.com:5443/v2.0'
              OS_TENANT_ID: '29h8gwh0wg0h2th0'
              OS_TENANT_NAME: 'project1'
              OS_USERNAME: 'project1'
              OS_PASSWORD: 'password1'
            project2:
              OS_AUTH_URL: 'https://identity.project2.openstack.com:5443/v2.0'
              OS_TENANT_ID: 'y4j0erg0j40'
              OS_TENANT_NAME: 'project2'
              OS_USERNAME: 'project2'
              OS_PASSWORD: 'password2'

#  - name: nova
#    run_list:
#      - recipe[openstack-clients::nova]
#  - name: glance
#    run_list:
#      - recipe[openstack-clients::glance]
#  - name: swift
#    run_list:
#      - recipe[openstack-clients::swift]
#  - name: ceilometer
#    run_list:
#      - recipe[openstack-clients::ceilometer]
#  - name: neutron
#    run_list:
#      - recipe[openstack-clients::neutron]
#  - name: cinder
#    run_list:
#      - recipe[openstack-clients::cinder]
#  - name: trove
#    run_list:
#      - recipe[openstack-clients::trove]
#  - name: barbican
#    run_list:
#      - recipe[openstack-clients::barbican]
#  - name: sahara
#    run_list:
#      - recipe[openstack-clients::sahara]
