---
driver:
  name: docker

provisioner:
  name: chef_zero
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: centos-6
- name: fedora-20
- name: fedora-21

suites:
- name: default
  run_list: ["recipe[openstack-clients]"]

- name: openstackrc
  run_list:
    - recipe[openstack-clients::openstackrc]
  attributes:
    openstack-clients:
      openstackrc:
        configs:
          project1:
            OS_AUTH_URL: 'https://identity.project1.openstack.com:5443/v2.0'
            OS_TENANT_ID: '29h8gwh0wg0h2th0'
            OS_TENANT_NAME: 'project1'
            OS_USERNAME: 'project1'
            OS_PASSWORD: 'password1'
          project2:
            OS_AUTH_URL: 'https://identity.project2.openstack.com:5443/v2.0'
            OS_TENANT_ID: 'y4j0erg0j40'
            OS_TENANT_NAME: 'project2'
            OS_USERNAME: 'project2'
            OS_PASSWORD: 'password2'
