rvm:
- 2.1
before_install:
- openssl aes-256-cbc -K $encrypted_2367e6cd31db_key -iv $encrypted_2367e6cd31db_iv
  -in travis-openstack-clients-cookbook.enc -out travis-openstack-clients-cookbook
  -d
install:
- bundle install --without vagrant
- bundle exec berks install
script:
- bundle exec rake travis
env:
  global:
  - secure: ZxjaOsUw4CG57rVxk0R2199f+ia+YnNm2z7xrLLHRZay3jjGI2W/iflzhQmRswU5Q0lg+EJXJCsSd0tF68Ho/yrp4MSaW5nX1es7/rcLZIBPiQCiJ7ImAldA4Sn/T8tMzJN6PHXiIv4Av2UxVlZ9+zgCbkp0jPX1EJ1xx9z4bGE=
  - secure: KMvWOLHd1Ff8PyXFqhhJl4EE0pHYqtS93cTEVaesXyvkJ9UN8DRUUmFkn6IxhYh2AhPihOE9l6PjJNnY6YV11ml/Ch473eGQ/YnTq5ify8Xl8BCY5gjCxeveNdkE46UY1Qi2B8I7a4I+d7t1JzuoRKTHAoBVuyOGsJFvE9ghOFY=
  - secure: T1jmlw2ucRPvbjvxih9/x/mS7yiAKw0dlQATr4IJ2FVCxtZerBbIoreYyWLyLfMCGmjyeLJcqdFhp8V4Adc9nxMe4APhRhUgxcfnPt2AKgGpFWL3Ivw7g5vVR/lIGrDJoo92i6C9PI58VaXDFTEKdR2UOfoz1yKjHIyxsMuoNwM=
  - secure: cJKX+bZFqozCyb3MEdGCTQ+YxdA1f/zp5MW6PDGq91vj9hwDjpag7tNU7S109l132c9B6O1xDuJ8u3F6Qu0EMlvhjNkgtAz8X93du7UCruVl6natgNOmi01t/Z3kXjc9b9Herd2tzhO7vBQFjKUTbOjP+XLTyGpsNIZjw3oHSNw=
