name 'openstack-clients'
maintainer 'Mike Splain'
maintainer_email 'mike.splain@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures openstack-clients'
long_description 'Installs/Configures openstack-clients'
version '0.2.2'

depends 'python', '~> 1.4'
depends 'apt', '~> 2.4'
depends 'yum-epel', '~> 0.3'
depends 'yum', '~> 3.2'
depends 'build-essential', '~> 2.0'
